
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './schema';

const SUPABASE_URL = "https://gfwqqqhaypwuuetyxuoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmd3FxcWhheXB3dXVldHl4dW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNjY1MDEsImV4cCI6MjA1OTc0MjUwMX0.nsQtLmyRorRp1i-XdUoVuO6WkuoxRMcKWP3xcdYql0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
